- args:
    sql: CREATE TABLE "public"."applications"("application_id" serial NOT NULL, "company"
      text NOT NULL, "stage_id" integer NOT NULL, PRIMARY KEY ("application_id") );
  type: run_sql
- args:
    name: applications
    schema: public
  type: add_existing_table_or_view
